const $=id=>document.getElementById(id),results=$('analysis-results');let version=0,analyzedCategory='';
const fmt=n=>Number.isInteger(n)?n.toLocaleString():n.toFixed(2);
const countryDialog=document.createElement('dialog');countryDialog.id='country-dialog';countryDialog.setAttribute('aria-labelledby','country-title');countryDialog.innerHTML='<div class="dialog-top"><h2 id="country-title"></h2><button id="country-close" aria-label="Close country gallery">✕</button></div><p id="country-status" role="status"></p><button id="country-retry" hidden>Retry</button><div id="country-images" class="analysis-images"></div><div class="pagination"><button id="country-previous">← Previous</button><span id="country-page"></span><button id="country-next">Next →</button></div>';document.body.append(countryDialog);
let countryRequest=0,countryName='',countryCategory='',countryPage=1;
async function loadCountry(page){
 const token=++countryRequest;countryPage=page;$('country-previous').disabled=$('country-next').disabled=true;$('country-images').replaceChildren();$('country-page').textContent='';$('country-retry').hidden=true;$('country-status').textContent='Loading country drawings…';
 try{const response=await fetch(`/api/country-drawings?category=${encodeURIComponent(countryCategory)}&country=${encodeURIComponent(countryName)}&page=${page}`);const data=await response.json();if(!response.ok)throw Error(data.error);if(token!==countryRequest)return;
 countryPage=data.page;for(const record of data.drawings)drawing($('country-images'),record,`${record.key_id} · ${record.recognized?'Recognized':'Unrecognized'}`);
 $('country-status').textContent=`${data.total.toLocaleString()} ${countryCategory} drawings from ${countryName}.`;$('country-page').textContent=`Page ${data.page} of ${data.pages}`;$('country-previous').disabled=data.page<=1;$('country-next').disabled=data.page>=data.pages;
 }catch(error){if(token===countryRequest){$('country-status').textContent=error.message;$('country-retry').hidden=false;}}
}
function openCountry(country){countryName=country;countryCategory=analyzedCategory;$('country-title').textContent=`${countryCategory} · ${country}`;countryDialog.showModal();loadCountry(1);}
$('country-close').onclick=()=>countryDialog.close();countryDialog.addEventListener('close',()=>countryRequest++);$('country-previous').onclick=()=>loadCountry(countryPage-1);$('country-next').onclick=()=>loadCountry(countryPage+1);$('country-retry').onclick=()=>loadCountry(countryPage);
function section(title,note){const s=document.createElement('section');s.className='analysis-section';const h=document.createElement('h2'),p=document.createElement('p');h.textContent=title;p.textContent=note;s.append(h,p);results.append(s);return s;}
function table(host,headers,rows,sortable=false){
 const wrap=document.createElement('div');wrap.className='table-wrap';const t=document.createElement('table'),head=document.createElement('tr'),body=document.createElement('tbody');
 let sortColumn=sortable?1:-1,ascending=false;
 function draw(){
  const ordered=[...rows];if(sortable)ordered.sort((a,b)=>{const x=a[sortColumn],y=b[sortColumn];const difference=typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y));return (ascending?1:-1)*difference;});
  body.replaceChildren();for(const row of ordered){const tr=document.createElement('tr');row.forEach((value,column)=>{const td=document.createElement('td');if(headers[0]==='Country'&&column===0){const button=document.createElement('button');button.className='country-link';button.textContent=value;button.onclick=()=>openCountry(value);td.append(button);}else td.textContent=typeof value==='number'?fmt(value):value;tr.append(td);});body.append(tr);}
  if(sortable)Array.from(head.children).forEach((th,i)=>{th.setAttribute('aria-sort',i===sortColumn?(ascending?'ascending':'descending'):'none');th.firstChild.textContent=headers[i]+(i===sortColumn?(ascending?' ↑':' ↓'):' ↕');});
 }
 headers.forEach((name,i)=>{const th=document.createElement('th');th.scope='col';if(sortable){const button=document.createElement('button');button.className='sort-heading';button.type='button';button.textContent=name;button.onclick=()=>{ascending=sortColumn===i?!ascending:i===0;sortColumn=i;draw();};th.append(button);}else th.textContent=name;head.append(th);});
 const thead=document.createElement('thead');thead.append(head);t.append(thead,body);wrap.append(t);host.append(wrap);draw();
}
function images(host){const div=document.createElement('div');div.className='analysis-images';host.append(div);return div;}
function figure(host,label){const f=document.createElement('figure'),c=document.createElement('canvas'),caption=document.createElement('figcaption');c.width=c.height=279;c.setAttribute('role','img');c.setAttribute('aria-label',label);caption.textContent=label;f.append(c,caption);host.append(f);return c.getContext('2d');}
function map(host,values,label,color=false){const ctx=figure(host,label),small=document.createElement('canvas');small.width=small.height=28;const s=small.getContext('2d'),im=s.createImageData(28,28),peak=Math.max(.00001,...values);for(let i=0;i<784;i++){const v=Math.min(1,values[i]/peak);im.data[i*4]=color?255:255*(1-v);im.data[i*4+1]=255*(1-v);im.data[i*4+2]=color?255*(1-v):255*(1-v);im.data[i*4+3]=255;}s.putImageData(im,0,0);ctx.drawImage(small,0,0,279,279);}
function drawing(host,r,label){const ctx=figure(host,label);let mx=0,my=0;for(const[x,y]of r.drawing){for(const v of x)mx=Math.max(mx,v);for(const v of y)my=Math.max(my,v);}ctx.translate(12+(255-mx)/2,12+(255-my)/2);ctx.strokeStyle='#263c26';ctx.lineWidth=3;ctx.lineCap='round';ctx.lineJoin='round';for(const[x,y]of r.drawing){if(!x.length)continue;ctx.beginPath();ctx.moveTo(x[0],y[0]);for(let i=1;i<x.length;i++)ctx.lineTo(x[i],y[i]);ctx.stroke();if(x.length===1){ctx.beginPath();ctx.arc(x[0],y[0],1.5,0,Math.PI*2);ctx.fill();}}}
function bars(host,entries,label){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 800 230');svg.setAttribute('role','img');svg.setAttribute('aria-label',label);const peak=Math.max(1,...entries.map(e=>e[1]));entries.forEach(([name,value],i)=>{const rect=document.createElementNS(ns,'rect'),w=740/entries.length;rect.setAttribute('x',45+i*w);rect.setAttribute('y',190-value/peak*170);rect.setAttribute('width',Math.max(1,w-2));rect.setAttribute('height',value/peak*170);rect.setAttribute('fill','#718a5f');const title=document.createElementNS(ns,'title');title.textContent=`${name}: ${value.toLocaleString()} drawings`;rect.append(title);svg.append(rect);if(i%Math.max(1,Math.ceil(entries.length/10))===0){const text=document.createElementNS(ns,'text');text.setAttribute('x',45+i*w);text.setAttribute('y',210);text.setAttribute('font-size','11');text.textContent=name;svg.append(text);}});const text=document.createElementNS(ns,'text');text.setAttribute('x','45');text.setAttribute('y','14');text.setAttribute('font-size','12');text.textContent=`${label} · peak ${peak.toLocaleString()} drawings`;svg.append(text);host.append(svg);const d=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Exact frequency table';d.append(summary);table(d,['Range','Drawings'],entries);host.append(d);}
function render(d){analyzedCategory=d.category;results.replaceChildren();
 let s=section('Stroke complexity',`All ${fmt(d.total)} drawings. Length is measured in the simplified 0–255 coordinate system, not physical drawing size.`);table(s,['Mean strokes','Mean stroke length'],[[d.summary.strokes,d.summary.length]]);bars(s,Object.entries(d.strokeBins).sort((a,b)=>Number(a[0])-Number(b[0])),'Number of strokes');bars(s,d.lengthBins.map((n,i)=>[i===20?'5000+':`${i*250}–${(i+1)*250}`,n]),'Total line length');
 s=section('Recognized vs unrecognized','Full category. These are associations with the original game’s recognition flag, not proof that a feature causes recognition.');table(s,['Group','Drawings','Mean strokes','Mean length','Mean symmetry'],Object.entries(d.recognition).map(([name,g])=>[name,g.count,g.strokes,g.length,g.symmetry]),true);
 s=section('Variation maps',`${d.sampleSize} evenly spaced drawings. Smoothed 28×28 occupancy; maps are contrast-scaled separately. Red marks greater disagreement, not simply more ink.`);let grid=images(s);map(grid,d.average,'Mean shape (sample)');map(grid,d.variation,'Pixel variation (sample)',true);
 s=section('Typical and unusual drawings',`${d.sampleSize}-drawing sample. Ranked by average squared distance to other smoothed shape masks. Typical examples have lower distance; unusual examples have higher distance. This measures geometry, not quality.`);grid=images(s);d.typical.forEach(r=>drawing(grid,r.record,`Typical · ${r.record.key_id}`));grid=images(s);d.unusual.forEach(r=>drawing(grid,r.record,`Unusual · ${r.record.key_id}`));
 s=section('Drawing-style clusters',`Up to six geometric groups from ${d.sampleSize} drawings using deterministic k-means. Groups are exploratory and may mix semantic styles. Counts refer only to the sample; means are contrast-scaled.`);grid=images(s);d.clusters.forEach((c,i)=>{map(grid,c.average,`Group ${i+1} · ${c.count} drawings`);drawing(grid,c.representative,`Group ${i+1} representative`);});
 s=section('Symmetry and proportions','Full category. Symmetry is mirrored ink overlap on centered 28×28 masks (0–1). Aspect ratio is bounding-box width divided by height, with a 1-unit stabilizer for flat strokes.');table(s,['Mean left–right symmetry','Mean aspect ratio'],[[d.summary.symmetry,d.summary.aspect]]);
 s=section('Stroke order',`${d.sampleSize}-drawing sample. Cumulative stroke-path density at one-third, two-thirds, and all strokes, keeping each drawing’s original centered frame. Each map is contrast-scaled. Stroke order is available; elapsed drawing time is not retained in simplified data.`);grid=images(s);d.order.forEach((v,i)=>map(grid,v,`${i+1}/3 of strokes`,true));
 s=section('Category similarity','Compares this category’s sampled mean shape to up to 48 drawings spread across each other downloaded category. Lower squared distance means more similar geometry. Rankings are exploratory; unequal sample sizes and shared simple shapes can affect them.');if(d.similarities.length)table(s,['Category','Comparison drawings','Shape distance'],d.similarities.map(r=>[r.category,r.count,r.distance.toFixed(5)]));else s.append('Download another category to compare it.');
 s=section('Country comparisons','Full category, grouped by recorded country code. Means and recognition rates allow comparisons across unequal counts, but small groups are unstable and players are not representative country samples. Differences are descriptive, not cultural conclusions.');table(s,['Country','Drawings','Recognition %','Mean strokes','Mean length','Mean symmetry'],d.countries.map(g=>[g.country,g.count,g.recognitionRate*100,g.strokes,g.length,g.symmetry]),true);
}
$('run-analysis').onclick=async()=>{const token=++version;const category=$('analysis-category').value;$('run-analysis').disabled=true;results.replaceChildren();$('analysis-status').textContent='Analyzing every drawing and building sampled shape comparisons… This may take a few minutes.';try{const response=await fetch('/api/analysis?category='+encodeURIComponent(category));const d=await response.json();if(!response.ok)throw Error(d.error);if(token!==version)return;render(d);$('analysis-status').textContent=`${category}: ${fmt(d.total)} drawings analyzed; ${d.sampleSize} used for shape exploration.`;}catch(e){$('analysis-status').textContent=e.message+' You can retry.';}finally{$('run-analysis').disabled=false;}};
fetch('/api/categories').then(r=>{if(!r.ok)throw Error('Could not load categories.');return r.json();}).then(cs=>{for(const c of cs){const o=document.createElement('option');o.value=c.name;o.textContent=c.name+(c.local?' · downloaded':'');$('analysis-category').append(o);}$('analysis-category').value='cat';}).catch(e=>{$('analysis-status').textContent=e.message;});
