  window.renderInkHistogram=function(data,chart,status){
    chart.replaceChildren();status.textContent=`${data.count.toLocaleString()} drawings · Mean coverage ${data.mean.toFixed(2)}% · Range ${data.min.toFixed(2)}–${data.max.toFixed(2)}%`;
    const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 800 260');svg.setAttribute('role','img');svg.setAttribute('aria-label',`Ink coverage frequency distribution for ${data.category}, ${data.count} drawings`);
    const element=(tag,attrs,text)=>{const el=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);if(text!==undefined)el.textContent=text;svg.append(el);return el;};
    const limit=Math.min(100,Math.max(5,Math.ceil((Math.floor(data.max)+1)/5)*5)),peak=Math.max(1,...data.bins),left=72,width=708,height=180;
    for(let tick=0;tick<=4;tick++){const y=20+height-tick*height/4;element('line',{x1:left,x2:780,y1:y,y2:y,stroke:'#e1e5db'});element('text',{x:left-8,y:y+4,'text-anchor':'end',class:'ink-label'},Math.round(peak*tick/4).toLocaleString());}
    for(let i=0;i<limit;i++){const h=data.bins[i]/peak*height;const rect=element('rect',{x:left+i*width/limit+1,y:200-h,width:Math.max(1,width/limit-2),height:h,fill:'#718a5f',tabindex:0});const title=document.createElementNS(ns,'title');title.textContent=`${i}–${i+1}% ink: ${data.bins[i].toLocaleString()} drawings`;rect.append(title);rect.setAttribute('aria-label',title.textContent);}
    for(let i=0;i<=5;i++)element('text',{x:left+width*i/5,y:222,'text-anchor':'middle',class:'ink-label'},`${(limit*i/5).toFixed(0)}%`);
    element('text',{x:426,y:248,'text-anchor':'middle',class:'ink-label'},'Image area covered by ink');element('text',{x:16,y:115,transform:'rotate(-90 16 115)','text-anchor':'middle',class:'ink-label'},'Drawings');chart.append(svg);
    const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='View frequency table';details.append(summary);const table=document.createElement('table');table.innerHTML='<thead><tr><th>Ink coverage</th><th>Drawings</th></tr></thead>';const body=document.createElement('tbody');for(let i=0;i<limit;i++){const row=document.createElement('tr');for(const text of [`${i}–${i+1}%`,data.bins[i].toLocaleString()]){const cell=document.createElement('td');cell.textContent=text;row.append(cell);}body.append(row);}table.append(body);details.append(table);chart.append(details);
  }
