(()=>{
 'use strict';
 const $=id=>document.getElementById(id),lab=window.momentsLab;
 const mass=(id,kg,position,label)=>({id,kg,position,label});
 const levels=[
  {title:'The overhanging book',art:'book',story:'A book rests beyond the edge of a long display shelf. A paperweight on the other side can stop the shelf tipping.',task:'Move paperweight B. Keep the book and table edge fixed.',setup:{length:4,pivot:3,masses:[mass(1,1,3.6,'Book'),mass(2,1,1.8,'Paperweight')]},edit:{2:['position']},hint:'The book is 0.6 m beyond the edge. Equal masses need equal perpendicular distances on opposite sides.'},
  {title:'Seesaw at the park',art:'seesaw',story:'Two toy figures share a seesaw. One is twice as heavy as the other. Where should the heavier figure sit?',task:'Move rider B along the beam. Rider A and the central pivot stay fixed.',setup:{length:6,pivot:3,masses:[mass(1,2,1,'Rider A'),mass(2,4,5,'Rider B')]},edit:{2:['position']},hint:'Rider A gives 2 × 9.81 × 2 N m anticlockwise. A mass twice as large needs half the lever arm.'},
  {title:'Wardrobe wobble',art:'wardrobe',story:'A miniature wardrobe is leaning past the edge of its base. Add a counterweight on the other side of the tipping edge.',task:'Add one 4 kg counterweight, then move it to balance the wardrobe load.',setup:{length:4,pivot:2.4,masses:[mass(1,12,2.8,'Wardrobe centre of mass')]},edit:{},add:{kg:4,position:1.5,label:'Counterweight'},addedEdit:['position'],hint:'The wardrobe contributes 12 × 0.4 × 9.81 N m. Divide this moment by the counterweight’s weight to find its lever arm.'},
  {title:'Market stall scales',art:'scales',story:'A fruit seller has a basket of apples on one side of an old balance. Choose the correct calibration mass on the other.',task:'Change mass B in kilograms. Both baskets stay in their marked positions.',setup:{length:6,pivot:3,masses:[mass(1,3,1,'Apples'),mass(2,1,5,'Calibration mass')]},edit:{2:['kg']},hint:'The two baskets have equal lever arms. Their weights must therefore be equal.'},
  {title:'The builders’ plank',art:'plank',story:'A toolbox and a bucket sit on a long plank. The builders can move the support, but the loads must stay put.',task:'Move the pivot until the loaded plank balances. The plank itself is treated as weightless.',setup:{length:8,pivot:4,masses:[mass(1,3,1,'Toolbox'),mass(2,2,6,'Bucket')]},edit:{},pivot:true,hint:'Set 3 × (pivot − 1) = 2 × (6 − pivot). Gravity cancels from both sides.'},
  {title:'Crane counterweight',art:'crane',story:'A model crane holds a load to the right of its tower. Its left-hand arm needs a counterweight.',task:'Add the 6 kg counterweight and slide it to balance the 4 kg suspended load.',setup:{length:8,pivot:3,masses:[mass(1,4,6,'Suspended load')]},edit:{},add:{kg:6,position:0,label:'Crane counterweight'},addedEdit:['position'],hint:'The load’s lever arm is 3 m. Use 4 × 3 = 6 × counterweight distance, measured from the tower.'},
  {title:'Bridge maintenance',art:'bridge',story:'A maintenance trolley stands on a uniform bridge deck. This time the deck has weight too, acting at its centre.',task:'Move ballast B to balance both the trolley and the 4 kg deck.',setup:{length:6,pivot:2,beamMass:4,masses:[mass(1,2,5,'Maintenance trolley'),mass(2,5,.5,'Ballast')]},edit:{2:['position']},hint:'The clockwise mass-distance total is 2 × (5 − 2) + 4 × (3 − 2). Ballast must counter both terms.'},
  {title:'A hanging mobile',art:'mobile',story:'Three ornaments hang from a mobile. Two positions are fixed; the third ornament can slide along its bar.',task:'Move ornament C. Include the moments from both fixed ornaments.',setup:{length:6,pivot:3,masses:[mass(1,1,0,'Moon ornament'),mass(2,2,4,'Star ornament'),mass(3,1,5,'Bird ornament')]},edit:{3:['position']},hint:'The moon contributes 3 kg m anticlockwise; the star contributes 2 kg m clockwise. C must supply the remaining clockwise moment.'},
  {title:'Camera boom',art:'camera',story:'A camera sits at the end of a studio boom. The operator can change and reposition its rear counterweight.',task:'Adjust counterweight B’s mass, position, or both. Keep the camera and pivot fixed.',setup:{length:6,pivot:2.5,masses:[mass(1,3,4.5,'Camera'),mass(2,1,.5,'Rear counterweight')]},edit:{2:['kg','position']},hint:'The camera contributes 3 × 2 = 6 kg m. Any allowed counterweight with mass × distance = 6 on the left will work.'},
  {title:'The festival sign',art:'sign',story:'Two lanterns hang from a uniform festival sign. Add one balancing weight, then decide where the support and weight should go.',task:'Add the 2 kg weight. Move it and/or the pivot to balance the sign, its own weight, and both lanterns.',setup:{length:8,pivot:4,beamMass:2,masses:[mass(1,2,1,'Left lantern'),mass(2,4,6,'Right lantern')]},edit:{},pivot:true,add:{kg:2,position:7,label:'Balancing weight'},addedEdit:['position'],hint:'One route: leave the pivot at 4 m. The sign’s own weight then has no moment, and your new weight must cancel the lanterns’ net moment.'}
 ];
 let active=false,index=0,completed=new Set(),saved=null,initialIds=[];
 const current=()=>levels[index];
 function allow(action,id,key){const l=current();if(action==='pivot')return !!l.pivot;if(action==='add')return !!l.add&&lab.state.masses.length===initialIds.length;if(action==='remove')return !initialIds.includes(id);if(action==='mass')return (initialIds.includes(id)?l.edit[id]||[]:l.addedEdit||[]).includes(key);return false;}
 function sync(){if(!active)return;for(const id of ['length','beam-mass'])$(id).disabled=true;$('pivot').disabled=!current().pivot;document.querySelectorAll('[data-pivot]').forEach(b=>b.disabled=!current().pivot);$('release').disabled=true;$('add').disabled=!allow('add');$('mode-note').textContent='Game mode holds the model level. Adjust the unlocked controls, then check the balance.';}
 function changed(){$('game-feedback').textContent='';}
 function policy(){return {scene:current().art,allow,sync,changed,newMass:current().add,retry:()=>load(index)};}
 function select(){const el=$('level-select');el.replaceChildren();const unlocked=Math.min(9,completed.size);levels.forEach((l,i)=>{const option=document.createElement('option');option.value=i;option.textContent=`${completed.has(i)?'✓ ':''}${i+1}. ${l.title}`;option.disabled=i>unlocked;el.append(option);});el.value=index;$('progress').textContent=`${completed.size} / 10 completed this session`;$('next-level').disabled=!completed.has(index)||index===9;}
 function art(type){const shape={book:'<path d="M30 105h180M55 105v35M185 105v35"/><path d="M135 67h70v34h-70z" fill="#b64223"/><path d="M70 82h28v20H70z" fill="#36715e"/>',wardrobe:'<path d="M85 30h75v105H85z" fill="#b8a181" transform="rotate(12 160 135)"/><path d="M123 40v88M110 80h4M136 80h4M55 140h140"/>',crane:'<path d="M110 140V30h100M30 45h180M170 45v58M160 103h25v25h-25zM55 45v30H30V45"/>',camera:'<path d="M30 90h180M120 90v50M173 62h34v25h-34zM207 70l15-7v24l-15-7M40 66h25v20H40z"/>',mobile:'<path d="M120 10v50M40 60h160M50 60v50M125 60v45M190 60v58"/><circle cx="50" cy="120" r="12" fill="#695695"/><path d="M125 100l5 12h13l-10 8 4 13-12-8-11 8 4-13-10-8h13z" fill="#b64223"/><path d="M180 120q14-16 27 0q-14 20-27 0" fill="#36715e"/>',sign:'<path d="M30 65h180M120 65v80M50 65v25M185 65v25M38 90h25v35H38zM173 90h25v35h-25z"/><path d="M75 40h90v23H75z" fill="#b8a181"/>',bridge:'<path d="M25 98h190M40 98v45M190 98v45M30 98q90-100 180 0M70 57v40M120 48v50M170 57v40M145 77h30v19h-30z"/>',scales:'<path d="M120 35v105M75 140h90M40 55h160M50 55v50M190 55v50M25 105q25 40 50 0zM165 105q25 40 50 0z"/>',plank:'<path d="M25 90h190M120 90l-28 50h56zM50 61h32v27H50zM165 65h26l-4 23h-18z"/>',seesaw:'<path d="M25 85h190M120 85l-28 55h56zM50 70v-20M185 70V45"/><circle cx="50" cy="38" r="11" fill="#b64223"/><circle cx="185" cy="32" r="15" fill="#36715e"/>'}[type];$('scenario-art').innerHTML=`<g stroke="#526347" stroke-width="4" stroke-linejoin="round" fill="none">${shape}</g>`;}
 function load(i){index=i;initialIds=current().setup.masses.map(m=>m.id);lab.setPolicy(policy());lab.loadSetup(current().setup);$('level-title').textContent=`${index+1}. ${current().title}`;$('scene-title').textContent=current().title;$('scene').setAttribute('aria-label',current().title+'. Drag the unlocked scenario objects or use the numeric controls to balance the moments.');document.querySelector('.scene-footer span').textContent='Drag unlocked objects or use the controls';$('level-story').textContent=current().story;$('level-task').textContent=current().task;$('hint-text').hidden=true;$('hint').textContent='Show hint';$('game-feedback').textContent='';art(current().art);select();sync();}
 function mode(game){if(game===active)return;if(game){saved=structuredClone(lab.state);active=true;$('game-panel').hidden=false;load(index);}else{active=false;lab.setPolicy(null);lab.loadSetup({...saved,running:false,angle:0,omega:0});$('game-panel').hidden=true;$('scene-title').textContent='Your beam';$('scene').setAttribute('aria-label','Interactive beam. Drag the beam, pivot or masses; numeric controls provide keyboard access.');document.querySelector('.scene-footer span').textContent='Drag the beam, pivot or masses';for(const id of ['length','beam-mass','pivot','release'])$(id).disabled=false;document.querySelectorAll('[data-pivot]').forEach(b=>b.disabled=false);}$('sandbox-mode').setAttribute('aria-pressed',!active);$('game-mode').setAttribute('aria-pressed',active);}
 $('sandbox-mode').addEventListener('click',()=>mode(false));$('game-mode').addEventListener('click',()=>mode(true));$('retry').addEventListener('click',()=>load(index));$('level-select').addEventListener('change',e=>{const i=Number(e.target.value);if(i<=completed.size)load(i);});$('hint').addEventListener('click',()=>{$('hint-text').textContent=current().hint;$('hint-text').hidden=!$('hint-text').hidden;$('hint').textContent=$('hint-text').hidden?'Show hint':'Hide hint';});$('next-level').addEventListener('click',()=>{if(completed.has(index)&&index<9)load(index+1);});
 $('check-balance').addEventListener('click',()=>{
  const result=lab.calculate(),l=current();
  if(l.add&&lab.state.masses.length!==initialIds.length+1){$('game-feedback').textContent='Add the counterweight specified in the challenge first.';return;}
  if(Math.abs(result.net)<=.2&&Math.abs(lab.state.angle)<1e-6&&result.cw>0&&result.ccw>0){completed.add(index);select();$('game-feedback').textContent=index===9?'Balanced! All ten challenges complete. You can revisit any level or return to the sandbox.':`Balanced! Clockwise ${result.cw.toFixed(2)} N m = anticlockwise ${result.ccw.toFixed(2)} N m. Next challenge unlocked.`;}
  else $('game-feedback').textContent=`Not balanced yet: ${Math.abs(result.net).toFixed(2)} N m ${result.net>0?'clockwise':'anticlockwise'}. Adjust an unlocked mass or pivot and try again.`;
 });
 window.momentsGame={levels,get active(){return active;},get index(){return index;},get completed(){return [...completed];}};
})();
