(()=>{
 'use strict';
 const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg',G=9.81,colors=['#b64223','#36715e','#695695','#9a6e24','#387991','#8d4667'];
 const state={length:6,pivot:3,beamMass:0,x:500,y:350,angle:0,omega:0,running:false,vectors:true,masses:[],nextId:1};
 let drag=null,last=0,accumulator=0,lastTable=0;
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 const fmt=(v,n=2)=>(Math.abs(v)<.0005?0:v).toFixed(n);
 const name=id=>String.fromCharCode(65+(id-1)%26);
 function scale(){return 75;}
 function setPivot(value){hold();state.x+=(value-state.pivot)*scale();state.pivot=value;}
 function moveBeam(dx,dy){const offset=(state.length/2-state.pivot)*scale();state.x=clamp(state.x+offset+dx,320,680)-offset;state.y=clamp(state.y+dy,290,410); }
 function point(position){const d=(position-state.pivot)*scale();return {x:state.x+d*Math.cos(state.angle),y:state.y+d*Math.sin(state.angle)};}
 function loads(){const a=state.masses.map(m=>({...m,label:'Mass '+name(m.id)}));if(state.beamMass>0)a.push({id:0,kg:state.beamMass,position:state.length/2,label:'Beam'});return a;}
 function calculate(){let cw=0,ccw=0;const rows=loads().map(m=>{const arm=(m.position-state.pivot)*Math.cos(state.angle),force=m.kg*G,moment=arm*force;if(moment>0)cw+=moment;else ccw-=moment;return {...m,arm,force,moment};});return {cw,ccw,net:cw-ccw,rows};}
 function inertia(){return state.beamMass*(state.length**2/12+(state.length/2-state.pivot)**2)+state.masses.reduce((sum,m)=>sum+m.kg*(m.position-state.pivot)**2,0);}
 function step(dt){if(!state.running)return;const i=inertia();if(i<1e-9){state.omega=0;return;}state.omega+=(calculate().net/i-.65*state.omega)*dt;state.angle+=state.omega*dt;state.angle=Math.atan2(Math.sin(state.angle),Math.cos(state.angle));}
 function node(tag,attrs={},text){const el=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))el.setAttribute(k,v);if(text!==undefined)el.textContent=text;return el;}
 function draw(){
  const svg=$('scene'),group=node('g');
  const radius=Math.max(state.pivot,state.length-state.pivot)*scale()+110;
  svg.setAttribute('viewBox',state.running?`${state.x-Math.max(500,radius)} ${state.y-Math.max(350,radius)} ${Math.max(1000,2*radius)} ${Math.max(700,2*radius)}`:'0 0 1000 700');
  const defs=node('defs');for(const [id,color]of [['weight','#695695'],['cw','#b64223'],['ccw','#36715e']]){const marker=node('marker',{id:'arrow-'+id,viewBox:'0 0 10 10',refX:8,refY:5,markerWidth:6,markerHeight:6,orient:'auto-start-reverse'});marker.append(node('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:color}));defs.append(marker);}group.append(defs);
  for(let x=0;x<=1000;x+=50)group.append(node('line',{x1:x,y1:0,x2:x,y2:700,stroke:'#d4ddca','stroke-width':1}));
  for(let y=0;y<=700;y+=50)group.append(node('line',{x1:0,y1:y,x2:1000,y2:y,stroke:'#d4ddca','stroke-width':1}));
  group.append(node('path',{d:`M ${state.x-30} ${state.y+48} L ${state.x} ${state.y} L ${state.x+30} ${state.y+48} Z`,fill:'#7a896b',stroke:'#526347','stroke-width':2,'data-drag':'pivot',class:'draggable'}));
  const a=point(0),b=point(state.length);group.append(node('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'#b8a181','stroke-width':22,'stroke-linecap':'round','data-drag':'beam',class:'draggable'}));
  for(let p=0;p<=state.length+.001;p+=.5){const q=point(p),s=Math.sin(state.angle),c=Math.cos(state.angle);group.append(node('line',{x1:q.x-6*s,y1:q.y+6*c,x2:q.x+6*s,y2:q.y-6*c,stroke:'#75634e','stroke-width':1.5,'pointer-events':'none'}));if(Number.isInteger(p))group.append(node('text',{x:q.x-26*s,y:q.y+26*c+4,'text-anchor':'middle',fill:'#625b4d','font-size':13},p+' m'));}
  group.append(node('circle',{cx:state.x,cy:state.y,r:10,fill:'#faf9f5',stroke:'#526347','stroke-width':3,'data-drag':'pivot',class:'draggable'}));
  group.append(node('text',{x:state.x,y:state.y+72,'text-anchor':'middle',fill:'#526347','font-size':13},'PIVOT · '+fmt(state.pivot,1)+' m'));
  const result=calculate();
  if(state.vectors){
   for(const m of result.rows){const q=point(m.position);if(m.kg<=0)continue;const len=36+Math.min(48,m.force*.25);group.append(node('line',{x1:q.x,y1:q.y+6,x2:q.x,y2:q.y+len,stroke:'#695695','stroke-width':3,'marker-end':'url(#arrow-weight)'}));group.append(node('text',{x:q.x+9,y:q.y+len-8,fill:'#695695','font-size':13},fmt(m.force,1)+' N'));
    if(Math.abs(m.moment)>.005){const cw=m.moment>0,r=40+(m.id%3)*15,sign=cw?1:-1;group.append(node('path',{d:`M ${q.x-r*.75} ${q.y-47} A ${r} ${r} 0 0 ${cw?1:0} ${q.x+r*.75} ${q.y-47}`,fill:'none',stroke:cw?'#b64223':'#36715e','stroke-width':2.5,'marker-end':`url(#arrow-${cw?'cw':'ccw'})`,'data-moment':cw?'cw':'ccw'}));group.append(node('text',{x:q.x,y:q.y-103,'text-anchor':'middle',fill:cw?'#b64223':'#36715e','font-size':12},fmt(Math.abs(m.moment),1)+' N m '+(sign>0?'↷':'↶')));}
   }
   group.append(node('text',{x:26,y:32,fill:'#695695','font-size':13},'↓ Weight    ↶ Anticlockwise    ↷ Clockwise'));
  }
  for(const m of state.masses){const q=point(m.position),color=colors[(m.id-1)%colors.length];group.append(node('circle',{cx:q.x,cy:q.y-22,r:22,fill:color,stroke:'#faf9f5','stroke-width':3,'data-drag':'mass','data-id':m.id,class:'draggable'}));group.append(node('text',{x:q.x,y:q.y-17,'text-anchor':'middle',fill:'#fff','font-size':14,'pointer-events':'none'},name(m.id)));group.append(node('text',{x:q.x,y:q.y-54,'text-anchor':'middle',fill:color,'font-size':14,'pointer-events':'none'},fmt(m.kg,1)+' kg'));}
  svg.replaceChildren(group);$('ccw').textContent=fmt(result.ccw)+' N m';$('cw').textContent=fmt(result.cw)+' N m';$('net').textContent=fmt(Math.abs(result.net))+' N m '+(Math.abs(result.net)<.005?'':result.net>0?'↷':'↶');
  $('status').textContent=state.running?(Math.abs(state.omega)<.002&&Math.abs(result.net)<.005?'Balanced':'Beam released'):Math.abs(result.net)<.005?'Balanced':result.net>0?'Clockwise moment':'Anticlockwise moment';$('angle').textContent=fmt(state.angle*180/Math.PI,1)+'°';
 }
 function table(){const body=$('moment-rows');body.replaceChildren();for(const m of calculate().rows){const tr=document.createElement('tr');for(const value of [m.label,fmt(m.force),fmt(m.position),fmt(Math.abs(m.arm)),fmt(Math.abs(m.moment)),Math.abs(m.moment)<.005?'None':m.moment>0?'Clockwise ↷':'Anticlockwise ↶']){const td=document.createElement('td');td.textContent=value;tr.append(td);}body.append(tr);}if(!body.children.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=6;td.textContent='Add a mass or give the beam a mass to explore turning moments.';tr.append(td);body.append(tr);}}
 function hold(){state.running=false;state.angle=0;state.omega=0;$('release').textContent='Release beam';$('mode-note').textContent='Beam held level while you arrange the experiment.';}
 function fields(){ $('length').value=state.length;$('beam-mass').value=state.beamMass;$('pivot').max=state.length;$('pivot').value=fmt(state.pivot,1);$('vectors').checked=state.vectors;const list=$('masses');list.replaceChildren();for(const m of state.masses){const row=document.createElement('div');row.className='mass-row';const label=document.createElement('span');label.className='mass-name';label.textContent=name(m.id);label.style.color=colors[(m.id-1)%colors.length];row.append(label);for(const [key,unit,min,max]of [['kg','kg',.1,20],['position','m',0,state.length]]){const l=document.createElement('label'),input=document.createElement('input');input.type='number';input.min=min;input.max=max;input.step=.1;input.value=fmt(m[key],1);input.setAttribute('aria-label','Mass '+name(m.id)+' '+(key==='kg'?'in kilograms':'position in metres'));input.addEventListener('change',()=>{const v=input.valueAsNumber;if(!Number.isFinite(v)){input.value=fmt(m[key],1);return;}m[key]=clamp(v,min,max);input.value=fmt(m[key],1);hold();table();});l.append(input,document.createTextNode(unit));row.append(l);}const remove=document.createElement('button');remove.className='remove';remove.textContent='×';remove.setAttribute('aria-label','Remove mass '+name(m.id));remove.addEventListener('click',()=>{state.masses=state.masses.filter(v=>v.id!==m.id);hold();fields();table();$('add').focus();});row.append(remove);list.append(row);}$('add').disabled=state.masses.length>=8;}
 function reset(){Object.assign(state,{length:6,pivot:3,beamMass:0,x:500,y:350,angle:0,omega:0,running:false,vectors:true,nextId:3,masses:[{id:1,kg:2,position:1},{id:2,kg:2,position:5}]});drag=null;hold();fields();table();draw();}
 for(const [id,key,min,max]of [['length','length',2,8],['beam-mass','beamMass',0,20],['pivot','pivot',0,8]])$(id).addEventListener('change',e=>{const value=e.target.valueAsNumber;if(!Number.isFinite(value)){fields();return;}const centre=state.x+(state.length/2-state.pivot)*scale();state[key]=clamp(value,min,key==='pivot'?state.length:max);state.pivot=Math.min(state.pivot,state.length);state.x=centre+(state.pivot-state.length/2)*scale();for(const m of state.masses)m.position=Math.min(m.position,state.length);hold();fields();table();});
 document.querySelectorAll('[data-pivot]').forEach(b=>b.addEventListener('click',()=>{setPivot(state.length*Number(b.dataset.pivot));fields();table();}));
 $('add').addEventListener('click',()=>{if(state.masses.length>=8)return;const id=state.nextId++;state.masses.push({id,kg:1,position:clamp(state.length/2+(state.masses.length%2?1:-1)*Math.ceil(state.masses.length/2)*.5,0,state.length)});hold();fields();table();const inputs=$('masses').querySelectorAll('input');inputs[inputs.length-2].focus();});
 $('vectors').addEventListener('change',e=>{state.vectors=e.target.checked;});$('reset').addEventListener('click',reset);$('release').addEventListener('click',()=>{if(state.running)hold();else{state.running=true;$('release').textContent='Hold level';$('mode-note').textContent='Beam rotates about the pivot. Masses stay attached. Editing the setup holds it level again.';}});
 const svg=$('scene');svg.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();hold();moveBeam(e.key==='ArrowRight'?10:e.key==='ArrowLeft'?-10:0,e.key==='ArrowDown'?10:e.key==='ArrowUp'?-10:0);});function coordinates(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());}
 svg.addEventListener('pointerdown',e=>{const target=e.target.closest('[data-drag]');if(!target||e.button!==0||drag)return;e.preventDefault();hold();const p=coordinates(e);drag={kind:target.dataset.drag,id:Number(target.dataset.id),pointer:e.pointerId,start:p,x:state.x,y:state.y,scale:scale(),pivot:state.pivot};svg.setPointerCapture(e.pointerId);});
 svg.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointer)return;const p=coordinates(e);if(drag.kind==='beam'){state.x=drag.x;state.y=drag.y;moveBeam(p.x-drag.start.x,p.y-drag.start.y);}else if(drag.kind==='pivot'){const pivot=clamp(drag.pivot+(p.x-drag.start.x)/drag.scale,0,state.length);state.pivot=Math.round(pivot*10)/10;state.x=drag.x+(state.pivot-drag.pivot)*drag.scale;$('pivot').value=fmt(state.pivot,1);}else{const m=state.masses.find(m=>m.id===drag.id);if(m)m.position=Math.round(clamp(state.pivot+(p.x-state.x)/scale(),0,state.length)*10)/10;}table();});
 function end(e){if(drag&&e.pointerId===drag.pointer){drag=null;fields();table();}}svg.addEventListener('pointerup',end);svg.addEventListener('pointercancel',end);svg.addEventListener('lostpointercapture',end);
 document.addEventListener('visibilitychange',()=>{last=0;accumulator=0;});
 function frame(now){if(last&&!document.hidden){accumulator+=Math.min((now-last)/1000,.1);while(accumulator>=1/120){step(1/120);accumulator-=1/120;}}last=now;draw();if(now-lastTable>100){table();lastTable=now;}requestAnimationFrame(frame);}
 reset();requestAnimationFrame(frame);window.momentsLab={state,calculate,inertia,step,reset,point};
})();
